
//首页顶部菜单
export const home_top =[
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
];


//首页中部菜单
export const home_mid =[
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    {icon:require('../constants/images/写跟进.png'),text:'写跟进'},
    {icon:require('../constants/images/建任务.png'),text:'建任务'},
    {icon:require('../constants/images/消息.png'),text:'消息'},
    {icon:require('../constants/images/录客户.png'),text:'录客户'},
    
   
];